[package]
name = "portfolio-site"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.14", features = ["csr", "tracing"] }
leptos_dom = { version = "0.6.14", features = ["csr"] }
leptos_meta = { version = "0.6.14", features = ["csr"] }
leptos_router = { version = "0.6.14", features = ["csr"] }
